-- :help options
vim.opt.number = true
vim.opt.smartindent = true
vim.opt.cursorline = true
vim.opt.signcolumn = 'yes'
vim.opt.smartindent = true
vim.opt.smartcase = true
vim.opt.mouse = 'a'
vim.opt.clipboard = 'unnamedplus'
vim.opt.termguicolors = true
vim.opt.wrap = false
vim.opt.hlsearch = true
vim.opt.fileencoding = "utf-8"
vim.opt.completeopt = {"menuone","noselect"}
vim.opt.tabstop = 2
vim.opt.scrolloff = 8
